name: Deploy my Lambda Function

on:
 push:
    branches:
        - main

jobs:
    lint:
        name: Validate code syntax
        runs-on: ubuntu-latest
        steps:
            - name: Check code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install libraries
              run: pip install flake8
            - name: Lint with flake8
              run: |
                cd function
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
                

    build:
        name: Build the code
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                 python-version: 3.8
            - name: Install libraries
              run: |
                cd function
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
            - name: Create zip bundle
              run: |
                cd function
                zip -r ../${{ github.sha }}.zip .
            - name: Archive artifact
              uses: actions/upload-artifact@v2
              with:
                name: zipped-bundle
                path: ${{ github.sha }}.zip 

    publish:
        name: Create a release
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create release
              id: create-release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: 1.0.2
                release_name: Release 1.0.2
                body: |
                    Changes in this release
                    - Adding lint step to pipeline
                    - Adding build step to pipeline
                    - Adding release step to pipeline
                draft: false
                prerelease: false
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                name: zipped-bundle
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create-release.outputs.upload_url }}
                asset_path: ./${{ github.sha }}.zip
                asset_name: source_code_with_libraries.zip
                asset_content_type: application/zip